package mem

import "console.store/internal/catalog"

// addresses is the signed-in user's saved set (mock).
var addresses = []catalog.Address{
	{ID: "a1", Label: "home", City: "Bangalore", Line: "HSR Layout", Full: "221, 5th Main, HSR Layout, Bangalore 560102", Lat: 12.9116, Lng: 77.6389},
	{ID: "a2", Label: "work", City: "Bangalore", Line: "Koramangala", Full: "WeWork, 80ft Rd, Koramangala, Bangalore 560034", Lat: 12.9352, Lng: 77.6245},
	{ID: "a3", Label: "mom", City: "Bangalore", Line: "Indiranagar", Full: "12, 100ft Rd, Indiranagar, Bangalore 560038", Lat: 12.9719, Lng: 77.6412},
}

// places is the curated whitelist (the moat). ServesAddressIDs models
// per-address serviceability that later comes from live search_restaurants.
var places = []catalog.Place{
	// ---- coffee ----
	{ID: "blue-tokai", Name: "Blue Tokai", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "35-45 min", Fav: true, Rating: 4.6,
		ServesAddressIDs: []string{"a1", "a2"}, Items: []catalog.Item{
			{ID: "bt-cold-coffee", Name: "Cold Coffee", Price: 149, Veg: true, Desc: "blended double espresso · lightly sweet", Kcal: 180, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "bt-hazelnut", Name: "Hazelnut Cold Brew", Price: 169, Veg: true, Desc: "16h steeped · hazelnut · no sugar", Kcal: 120, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "bt-viet", Name: "Vietnamese Cold Brew", Price: 159, Tag: "new", Veg: true, Desc: "robusta · condensed milk · intense", Kcal: 160, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "bt-croissant", Name: "Almond Croissant", Price: 129, Veg: true, Desc: "flaky · frangipane · toasted almonds", Kcal: 430, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "bt-banana", Name: "Banana Bread Slice", Price: 99, Veg: true, Desc: "walnut · moist · baked daily", Kcal: 290, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "bt-latte", Name: "Oat Milk Latte", Price: 179, Veg: true, Desc: "single origin · oat milk · no dairy", Kcal: 140, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "bt-americano", Name: "Americano", Price: 119, Veg: true, Desc: "double shot · hot or iced · bright", Kcal: 10, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "bt-chai", Name: "Masala Chai", Price: 99, Veg: true, Desc: "ginger · cardamom · whole milk · frothy", Kcal: 120, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "bt-brownie", Name: "Chocolate Fudge Brownie", Price: 119, Veg: true, Desc: "dark chocolate · fudgy · sea salt finish", Kcal: 380, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "bt-sandwich", Name: "Chicken Club Sandwich", Price: 189, Veg: false, Desc: "grilled chicken · cheddar · lettuce · mustard", Kcal: 520, Rating: 4.3, Section: catalog.SectionCoffee},
		}},
	{ID: "third-wave", Name: "Third Wave", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "30-40 min", Rating: 4.5,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "tw-flat-white", Name: "Flat White", Price: 159, Veg: true, Desc: "double ristretto · silky microfoam", Kcal: 130, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "tw-filter", Name: "Filter Coffee", Price: 99, Veg: true, Desc: "south-indian · chicory blend · frothy", Kcal: 90, Rating: 4.9, Section: catalog.SectionCoffee},
			{ID: "tw-cold-brew", Name: "Cold Brew Tonic", Price: 179, Tag: "new", Veg: true, Desc: "cold brew · tonic water · lime peel", Kcal: 45, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "tw-cortado", Name: "Cortado", Price: 139, Veg: true, Desc: "equal parts espresso and warm milk", Kcal: 80, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "tw-matcha", Name: "Matcha Latte", Price: 169, Veg: true, Desc: "ceremonial grade · oat milk · earthy", Kcal: 150, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "tw-croissant", Name: "Plain Butter Croissant", Price: 109, Veg: true, Desc: "laminated dough · golden · flaky layers", Kcal: 380, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "tw-muffin", Name: "Blueberry Muffin", Price: 89, Veg: true, Desc: "wild blueberry · streusel top · moist crumb", Kcal: 320, Rating: 4.3, Section: catalog.SectionCoffee},
			{ID: "tw-granola", Name: "Granola Parfait", Price: 149, Veg: true, Desc: "house granola · greek yogurt · seasonal fruit", Kcal: 280, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "tw-avocado-toast", Name: "Avocado Toast", Price: 199, Veg: true, Desc: "sourdough · smashed avocado · chilli flakes", Kcal: 350, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "tw-cappuccino", Name: "Cappuccino", Price: 129, Veg: true, Desc: "double shot · velvety foam · dusted cocoa", Kcal: 110, Rating: 4.6, Section: catalog.SectionCoffee},
		}},
	{ID: "sleepy-owl", Name: "Sleepy Owl", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "40-50 min", Rating: 4.3,
		ServesAddressIDs: []string{"a2", "a3"}, Items: []catalog.Item{
			{ID: "so-cold-brew", Name: "Cold Brew Original", Price: 129, Tag: "new", Veg: true, Desc: "smooth · low-acid · 18h steep", Kcal: 25, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "so-mocha", Name: "Mocha Cold Brew", Price: 149, Veg: true, Desc: "dark cocoa · cold brew · oat milk", Kcal: 150, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "so-hazelnut-brew", Name: "Hazelnut Brew", Price: 149, Veg: true, Desc: "cold brew · hazelnut syrup · no sugar added", Kcal: 90, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "so-mint", Name: "Mint Cold Brew", Price: 139, Veg: true, Desc: "cold brew · fresh mint · refreshing", Kcal: 30, Rating: 4.3, Section: catalog.SectionCoffee},
			{ID: "so-oat-brew", Name: "Oat Milk Cold Brew", Price: 159, Veg: true, Desc: "cold brew · creamy oat milk · barista blend", Kcal: 120, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "so-overnight-pack", Name: "Overnight Brew Pack (5 bags)", Price: 199, Veg: true, Desc: "steep at home · 5 single-use bags · arabica", Kcal: 0, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "so-instant-tubes", Name: "Instant Coffee Tubes (10pk)", Price: 149, Veg: true, Desc: "just add water · no bitterness · office pack", Kcal: 15, Rating: 4.2, Section: catalog.SectionCoffee},
			{ID: "so-french-roast", Name: "French Roast Cold Brew", Price: 139, Veg: true, Desc: "dark roast · bold · slightly smoky", Kcal: 20, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "so-vanilla", Name: "Vanilla Cold Brew", Price: 149, Veg: true, Desc: "madagascar vanilla · cold brew · smooth finish", Kcal: 80, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "so-choco-almond", Name: "Choco Almond Brew", Price: 159, Veg: true, Desc: "cold brew · almond milk · dark chocolate", Kcal: 130, Rating: 4.3, Section: catalog.SectionCoffee},
		}},
	{ID: "subko", Name: "Subko", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "45-55 min", Rating: 4.7,
		ServesAddressIDs: []string{"a3"}, Items: []catalog.Item{
			{ID: "sk-pour", Name: "Single-Origin Pour", Price: 179, Veg: true, Desc: "rotating estate · bright · hand-poured", Kcal: 5, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "sk-bun", Name: "Cardamom Bun", Price: 139, Veg: true, Desc: "cardamom · pearl sugar · fresh", Kcal: 340, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "sk-espresso", Name: "Double Espresso", Price: 149, Veg: true, Desc: "in-house blend · crema · intense finish", Kcal: 10, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "sk-cold-latte", Name: "Cold Brew Latte", Price: 199, Veg: true, Desc: "24h cold brew · full fat milk · gentle sweet", Kcal: 160, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "sk-oat-flat", Name: "Oat Flat White", Price: 209, Tag: "new", Veg: true, Desc: "double ristretto · oat milk · smooth texture", Kcal: 130, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "sk-banana-loaf", Name: "Banana Walnut Loaf", Price: 129, Veg: true, Desc: "ripe banana · toasted walnut · moist slice", Kcal: 310, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "sk-cheese-toast", Name: "Grilled Cheese Toast", Price: 159, Veg: true, Desc: "sourdough · aged cheddar · dijon mustard", Kcal: 420, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "sk-lemon-cake", Name: "Lemon Drizzle Cake", Price: 149, Veg: true, Desc: "sharp lemon curd · light sponge · glazed", Kcal: 360, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "sk-darjeeling", Name: "Darjeeling First Flush", Price: 169, Veg: true, Desc: "single estate · muscatel · light brew", Kcal: 5, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "sk-tonic-espresso", Name: "Espresso Tonic", Price: 189, Veg: true, Desc: "double shot over tonic water · citrus peel", Kcal: 20, Rating: 4.8, Section: catalog.SectionCoffee},
		}},
	{ID: "roastery-coffee", Name: "Roastery Coffee House", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "30-40 min", Fav: true, Rating: 4.6,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "rc-signature-cold", Name: "Signature Cold Coffee", Price: 159, Veg: true, Desc: "house blend · cold brewed · creamy", Kcal: 170, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "rc-pour-over", Name: "Pour Over", Price: 169, Veg: true, Desc: "single origin arabica · clean cup · floral", Kcal: 8, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "rc-dirty-chai", Name: "Dirty Chai", Price: 179, Veg: true, Desc: "masala chai · espresso shot · warming spice", Kcal: 145, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "rc-iced-latte", Name: "Iced Caramel Latte", Price: 189, Veg: true, Desc: "espresso · salted caramel · iced milk", Kcal: 220, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "rc-filter", Name: "South Indian Filter Coffee", Price: 89, Veg: true, Desc: "decoction · full cream milk · traditional", Kcal: 95, Rating: 4.9, Section: catalog.SectionCoffee},
			{ID: "rc-mango-shake", Name: "Mango Lassi Shake", Price: 149, Veg: true, Desc: "alphonso mango · yogurt · chilled", Kcal: 210, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "rc-panini", Name: "Grilled Veg Panini", Price: 179, Veg: true, Desc: "roasted peppers · mozzarella · pesto", Kcal: 450, Rating: 4.3, Section: catalog.SectionCoffee},
			{ID: "rc-chicken-panini", Name: "Chicken Pesto Panini", Price: 209, Veg: false, Desc: "grilled chicken · basil pesto · sun-dried tomato", Kcal: 530, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "rc-choco-muffin", Name: "Double Chocolate Muffin", Price: 99, Veg: true, Desc: "dark cocoa · chocolate chips · tender crumb", Kcal: 340, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "rc-brownie-jar", Name: "Brownie in a Jar", Price: 139, Tag: "new", Veg: true, Desc: "fudge brownie · vanilla cream · layered", Kcal: 410, Rating: 4.7, Section: catalog.SectionCoffee},
		}},
	{ID: "maverick-farmer", Name: "Maverick & Farmer", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "35-45 min", Rating: 4.5,
		ServesAddressIDs: []string{"a1", "a3"}, Items: []catalog.Item{
			{ID: "mf-cold-brew", Name: "Cold Brew Classic", Price: 149, Veg: true, Desc: "12h steep · smooth · zero bitterness", Kcal: 20, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "mf-espresso-tonic", Name: "Espresso & Tonic", Price: 179, Tag: "new", Veg: true, Desc: "single origin · fever tree tonic · lime", Kcal: 25, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "mf-iced-cappuccino", Name: "Iced Cappuccino", Price: 159, Veg: true, Desc: "double shot · cold frothed milk · no sugar", Kcal: 110, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "mf-hojicha", Name: "Hojicha Latte", Price: 169, Veg: true, Desc: "roasted japanese green tea · oat milk · earthy", Kcal: 130, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "mf-affogato", Name: "Affogato", Price: 189, Veg: true, Desc: "vanilla gelato · double espresso · immediate serve", Kcal: 240, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "mf-tiramisu", Name: "Tiramisu Slice", Price: 169, Veg: true, Desc: "lady fingers · mascarpone · espresso soak", Kcal: 390, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "mf-cheesecake", Name: "New York Cheesecake", Price: 179, Veg: true, Desc: "cream cheese · graham cracker base · berry coulis", Kcal: 450, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "mf-egg-sandwich", Name: "Egg & Cheese Sandwich", Price: 159, Veg: false, Desc: "scrambled egg · cheddar · multigrain bread", Kcal: 490, Rating: 4.3, Section: catalog.SectionCoffee},
			{ID: "mf-veg-wrap", Name: "Hummus Veggie Wrap", Price: 149, Veg: true, Desc: "whole wheat wrap · hummus · cucumber · greens", Kcal: 320, Rating: 4.2, Section: catalog.SectionCoffee},
			{ID: "mf-granola-bowl", Name: "Acai Granola Bowl", Price: 199, Veg: true, Desc: "acai base · house granola · banana · honey", Kcal: 310, Rating: 4.5, Section: catalog.SectionCoffee},
		}},
	{ID: "dyu-art-cafe", Name: "Dyu Art Cafe", City: "Bangalore", Section: catalog.SectionCoffee, ETA: "40-50 min", Rating: 4.4,
		ServesAddressIDs: []string{"a2", "a3"}, Items: []catalog.Item{
			{ID: "da-filter-coffee", Name: "Classic Filter Coffee", Price: 90, Veg: true, Desc: "traditional decoction · full cream · frothy", Kcal: 90, Rating: 4.8, Section: catalog.SectionCoffee},
			{ID: "da-cold-coffee", Name: "Dyu Cold Coffee", Price: 145, Veg: true, Desc: "house blend · chilled milk · lightly sweetened", Kcal: 175, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "da-rose-latte", Name: "Rose Latte", Price: 165, Tag: "new", Veg: true, Desc: "espresso · rose syrup · steamed milk · floral", Kcal: 155, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "da-ginger-tea", Name: "Ginger Lemon Tea", Price: 99, Veg: true, Desc: "fresh ginger · lemon · honey · warm", Kcal: 40, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "da-hot-choc", Name: "Belgian Hot Chocolate", Price: 155, Veg: true, Desc: "valrhona cocoa · steamed milk · rich finish", Kcal: 260, Rating: 4.6, Section: catalog.SectionCoffee},
			{ID: "da-quiche", Name: "Spinach & Feta Quiche", Price: 169, Veg: true, Desc: "shortcrust pastry · wilted spinach · feta", Kcal: 380, Rating: 4.4, Section: catalog.SectionCoffee},
			{ID: "da-bruschetta", Name: "Tomato Bruschetta", Price: 139, Veg: true, Desc: "toasted ciabatta · cherry tomato · basil", Kcal: 290, Rating: 4.3, Section: catalog.SectionCoffee},
			{ID: "da-pasta", Name: "Penne Arrabiata", Price: 199, Veg: true, Desc: "penne · spicy tomato · garlic · parmesan", Kcal: 520, Rating: 4.5, Section: catalog.SectionCoffee},
			{ID: "da-choc-fondant", Name: "Chocolate Fondant", Price: 185, Veg: true, Desc: "warm lava cake · vanilla ice cream · decadent", Kcal: 460, Rating: 4.7, Section: catalog.SectionCoffee},
			{ID: "da-fruit-tart", Name: "Mixed Berry Tart", Price: 159, Veg: true, Desc: "shortcrust · pastry cream · seasonal berries", Kcal: 340, Rating: 4.6, Section: catalog.SectionCoffee},
		}},
	// ---- food ----
	{ID: "california-burrito", Name: "California Burrito", City: "Bangalore", Section: catalog.SectionFood, ETA: "35-45 min", Rating: 4.4,
		ServesAddressIDs: []string{"a1", "a2"}, Items: []catalog.Item{
			{ID: "cb-chicken-burrito", Name: "Chicken Burrito", Price: 289, Desc: "grilled chicken · rice · beans · salsa", Kcal: 640, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "cb-veg-bowl", Name: "Veg Burrito Bowl", Price: 249, Veg: true, Desc: "cilantro rice · beans · guac · no tortilla", Kcal: 520, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "cb-nachos", Name: "Loaded Nachos", Price: 179, Veg: true, Desc: "cheese · jalapeño · beans · sour cream", Kcal: 480, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "cb-chicken-quesadilla", Name: "Chicken Quesadilla", Price: 259, Veg: false, Desc: "flour tortilla · spiced chicken · cheddar · salsa", Kcal: 580, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "cb-veg-taco", Name: "Veg Taco (3 pcs)", Price: 219, Veg: true, Desc: "corn tortilla · black beans · pico de gallo · guac", Kcal: 430, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "cb-chicken-taco", Name: "Chicken Taco (3 pcs)", Price: 259, Veg: false, Desc: "corn tortilla · chipotle chicken · cotija cheese", Kcal: 510, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "cb-elote", Name: "Mexican Street Corn", Price: 149, Veg: true, Desc: "charred corn · chilli mayo · cotija · lime", Kcal: 280, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "cb-churros", Name: "Churros with Dip", Price: 159, Veg: true, Desc: "cinnamon sugar · chocolate dipping sauce", Kcal: 380, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "cb-horchata", Name: "Horchata", Price: 99, Veg: true, Desc: "rice milk · cinnamon · chilled", Kcal: 140, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "cb-jalapeno-poppers", Name: "Jalapeño Poppers", Price: 169, Veg: true, Desc: "cream cheese stuffed · crispy panko coating", Kcal: 320, Rating: 4.4, Section: catalog.SectionFood},
		}},
	{ID: "leon-grill", Name: "Leon Grill", City: "Bangalore", Section: catalog.SectionFood, ETA: "30-40 min", Rating: 4.2,
		ServesAddressIDs: []string{"a1", "a3"}, Items: []catalog.Item{
			{ID: "lg-shawarma", Name: "Chicken Shawarma", Price: 199, Desc: "garlic · pickle · toasted lavash", Kcal: 560, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "lg-falafel", Name: "Falafel Wrap", Price: 169, Veg: true, Desc: "crisp falafel · hummus · tahini", Kcal: 430, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "lg-seekh-kebab", Name: "Seekh Kebab Platter", Price: 259, Veg: false, Desc: "minced lamb · charcoal grill · mint chutney", Kcal: 490, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "lg-hummus-plate", Name: "Hummus Platter", Price: 189, Veg: true, Desc: "chickpea hummus · pita · olive oil · paprika", Kcal: 380, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "lg-mixed-grill", Name: "Mixed Grill Platter", Price: 399, Veg: false, Desc: "chicken tikka · seekh kebab · grilled prawns · slaw", Kcal: 720, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "lg-paneer-tikka", Name: "Paneer Tikka Wrap", Price: 179, Veg: true, Desc: "charred paneer · bell pepper · tikka spice · lavash", Kcal: 460, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "lg-pita-chips", Name: "Pita Chips & Dips", Price: 129, Veg: true, Desc: "baked pita · hummus · baba ganoush · tzatziki", Kcal: 310, Rating: 4.2, Section: catalog.SectionFood},
			{ID: "lg-lemon-rice", Name: "Lemon Rice", Price: 149, Veg: true, Desc: "basmati · lemon tempering · curry leaf · peanut", Kcal: 290, Rating: 4.1, Section: catalog.SectionFood},
			{ID: "lg-lamb-pita", Name: "Lamb Pita Burger", Price: 239, Veg: false, Desc: "spiced lamb patty · pita · tzatziki · tomato", Kcal: 580, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "lg-mint-lemonade", Name: "Mint Lemonade", Price: 89, Veg: true, Desc: "fresh mint · squeezed lemon · soda water", Kcal: 60, Rating: 4.4, Section: catalog.SectionFood},
		}},
	{ID: "freshmenu", Name: "FreshMenu", City: "Bangalore", Section: catalog.SectionFood, ETA: "40-50 min", Rating: 4.1,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "fm-thai-rice", Name: "Thai Basil Rice", Price: 269, Veg: true, Desc: "holy basil · chilli · jasmine rice", Kcal: 610, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "fm-butter-chicken", Name: "Butter Chicken Meal", Price: 319, Desc: "makhani gravy · rice · butter naan", Kcal: 780, Rating: 4.8, Section: catalog.SectionFood},
			{ID: "fm-pasta", Name: "Penne Arrabiata", Price: 249, Veg: true, Desc: "san marzano · garlic · fresh basil · penne", Kcal: 550, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "fm-chicken-biryani", Name: "Chicken Biryani", Price: 299, Veg: false, Desc: "dum cooked · long grain rice · raita · salan", Kcal: 720, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "fm-dal-makhani", Name: "Dal Makhani Meal", Price: 259, Veg: true, Desc: "black lentil · cream · butter naan · rice", Kcal: 680, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "fm-caesar", Name: "Grilled Chicken Caesar", Price: 289, Veg: false, Desc: "romaine · parmesan · croutons · grilled chicken", Kcal: 420, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "fm-mushroom-risotto", Name: "Mushroom Risotto", Price: 299, Veg: true, Desc: "arborio rice · porcini · parmesan · truffle oil", Kcal: 590, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "fm-fish-curry", Name: "Fish Curry Meal", Price: 329, Veg: false, Desc: "coastal gravy · steamed rice · papad · pickle", Kcal: 650, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "fm-veg-soup", Name: "Cream of Tomato Soup", Price: 149, Veg: true, Desc: "fresh tomato · cream · basil oil · bread roll", Kcal: 220, Rating: 4.2, Section: catalog.SectionFood},
			{ID: "fm-gulab-jamun", Name: "Gulab Jamun (2 pcs)", Price: 99, Veg: true, Desc: "khoya balls · rose syrup · warm · saffron", Kcal: 280, Rating: 4.4, Section: catalog.SectionFood},
		}},
	{ID: "meghana-foods", Name: "Meghana Foods", City: "Bangalore", Section: catalog.SectionFood, ETA: "35-45 min", Fav: true, Rating: 4.7,
		ServesAddressIDs: []string{"a1", "a2"}, Items: []catalog.Item{
			{ID: "mgh-chicken-biryani", Name: "Chicken Biryani", Price: 299, Veg: false, Desc: "dum biryani · kachi method · raita · salan", Kcal: 740, Rating: 4.9, Section: catalog.SectionFood},
			{ID: "mgh-mutton-biryani", Name: "Mutton Biryani", Price: 369, Veg: false, Desc: "slow cooked mutton · fragrant rice · fried onion", Kcal: 820, Rating: 4.8, Section: catalog.SectionFood},
			{ID: "mgh-veg-biryani", Name: "Veg Biryani", Price: 239, Veg: true, Desc: "seasonal vegetables · saffron rice · mint", Kcal: 590, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "mgh-chicken-tikka", Name: "Chicken Tikka (6 pcs)", Price: 329, Veg: false, Desc: "boneless thigh · tandoor · mint chutney", Kcal: 480, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "mgh-paneer-butter-masala", Name: "Paneer Butter Masala", Price: 259, Veg: true, Desc: "cottage cheese · makhani gravy · butter naan", Kcal: 620, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "mgh-dal-tadka", Name: "Dal Tadka", Price: 189, Veg: true, Desc: "yellow lentil · mustard tadka · ghee", Kcal: 340, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "mgh-tandoori-roti", Name: "Tandoori Roti (4 pcs)", Price: 89, Veg: true, Desc: "whole wheat · tandoor char · served hot", Kcal: 240, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "mgh-butter-naan", Name: "Butter Naan (2 pcs)", Price: 79, Veg: true, Desc: "maida · butter glaze · soft · fluffy", Kcal: 300, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "mgh-raita", Name: "Boondi Raita", Price: 69, Veg: true, Desc: "yogurt · boondi · cumin · chilled", Kcal: 120, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "mgh-phirni", Name: "Phirni", Price: 99, Veg: true, Tag: "new", Desc: "rice pudding · saffron · cardamom · chilled", Kcal: 230, Rating: 4.6, Section: catalog.SectionFood},
		}},
	{ID: "truffles-restaurant", Name: "Truffles", City: "Bangalore", Section: catalog.SectionFood, ETA: "30-40 min", Rating: 4.5,
		ServesAddressIDs: []string{"a2", "a3"}, Items: []catalog.Item{
			{ID: "tr-classic-burger", Name: "Classic Beef Burger", Price: 349, Veg: false, Desc: "beef patty · cheddar · pickles · truffle mayo", Kcal: 720, Rating: 4.8, Section: catalog.SectionFood},
			{ID: "tr-chicken-burger", Name: "Crispy Chicken Burger", Price: 299, Veg: false, Desc: "buttermilk fried chicken · coleslaw · sriracha", Kcal: 650, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "tr-veg-burger", Name: "The Veg Burger", Price: 259, Veg: true, Desc: "black bean patty · avocado · lettuce · pickled onion", Kcal: 540, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "tr-loaded-fries", Name: "Loaded Cheese Fries", Price: 219, Veg: true, Desc: "crinkle fries · nacho cheese · jalapenos · sour cream", Kcal: 680, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "tr-mac-cheese", Name: "Mac & Cheese", Price: 249, Veg: true, Desc: "elbow pasta · four cheese sauce · breadcrumb top", Kcal: 610, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "tr-wings", Name: "Buffalo Wings (6 pcs)", Price: 319, Veg: false, Desc: "crispy wings · buffalo sauce · blue cheese dip", Kcal: 540, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "tr-onion-rings", Name: "Onion Rings", Price: 149, Veg: true, Desc: "beer batter · crispy · chipotle dip", Kcal: 380, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "tr-milkshake", Name: "Oreo Milkshake", Price: 199, Veg: true, Tag: "new", Desc: "vanilla ice cream · oreo crumble · whipped cream", Kcal: 490, Rating: 4.8, Section: catalog.SectionFood},
			{ID: "tr-brownie-shake", Name: "Brownie Shake", Price: 219, Veg: true, Desc: "chocolate ice cream · warm brownie · caramel drizzle", Kcal: 560, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "tr-lemonade", Name: "Virgin Mojito", Price: 119, Veg: true, Desc: "lime · mint · soda · crushed ice", Kcal: 70, Rating: 4.4, Section: catalog.SectionFood},
		}},
	{ID: "empire-restaurant", Name: "Empire Restaurant", City: "Bangalore", Section: catalog.SectionFood, ETA: "25-35 min", Rating: 4.3,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "er-chicken-roll", Name: "Chicken Roll", Price: 139, Veg: false, Desc: "egg roll · spiced chicken · onion · chutney", Kcal: 420, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "er-mutton-roll", Name: "Mutton Roll", Price: 169, Veg: false, Desc: "egg roll · tender mutton · green chutney", Kcal: 470, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "er-veg-roll", Name: "Veg Roll", Price: 109, Veg: true, Desc: "egg roll · paneer bhurji · onion · mint chutney", Kcal: 360, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "er-chicken-biryani", Name: "Empire Chicken Biryani", Price: 199, Veg: false, Desc: "signature masala · long grain rice · raita", Kcal: 680, Rating: 4.8, Section: catalog.SectionFood},
			{ID: "er-chicken-curry", Name: "Chicken Curry Meal", Price: 219, Veg: false, Desc: "home-style gravy · rice · parota", Kcal: 720, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "er-parota", Name: "Kerala Parota (3 pcs)", Price: 69, Veg: true, Desc: "layered wheat parota · crispy edges · soft inside", Kcal: 330, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "er-egg-curry", Name: "Egg Curry Meal", Price: 179, Veg: false, Desc: "boiled eggs · spicy onion gravy · rice", Kcal: 580, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "er-masala-dosa", Name: "Masala Dosa", Price: 109, Veg: true, Desc: "crisp dosa · potato masala · sambar · chutney", Kcal: 450, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "er-fish-fry", Name: "Fish Fry Platter", Price: 249, Veg: false, Desc: "pomfret · coastal masala · lemon · kumkum rice", Kcal: 540, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "er-cool-drinks", Name: "Rose Milk", Price: 59, Veg: true, Desc: "rose syrup · chilled full cream milk · sweet", Kcal: 130, Rating: 4.2, Section: catalog.SectionFood},
		}},
	{ID: "bowl-company", Name: "The Bowl Company", City: "Bangalore", Section: catalog.SectionFood, ETA: "40-50 min", Rating: 4.2,
		ServesAddressIDs: []string{"a1", "a3"}, Items: []catalog.Item{
			{ID: "bc-korean-bowl", Name: "Korean Bibimbap Bowl", Price: 299, Veg: true, Desc: "steamed rice · gochujang · mixed vegetables · fried egg", Kcal: 580, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "bc-chicken-teriyaki", Name: "Chicken Teriyaki Bowl", Price: 319, Veg: false, Desc: "teriyaki chicken · steamed rice · sesame · spring onion", Kcal: 640, Rating: 4.7, Section: catalog.SectionFood},
			{ID: "bc-poke-bowl", Name: "Tuna Poke Bowl", Price: 369, Veg: false, Desc: "ahi tuna · sushi rice · edamame · avocado · ponzu", Kcal: 520, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "bc-mediterranean", Name: "Mediterranean Bowl", Price: 279, Veg: true, Desc: "quinoa · falafel · tzatziki · roasted veg · feta", Kcal: 490, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "bc-mexican-bowl", Name: "Mexican Bowl", Price: 269, Veg: true, Desc: "cilantro rice · black beans · guac · pico · corn", Kcal: 530, Rating: 4.5, Section: catalog.SectionFood},
			{ID: "bc-thai-bowl", Name: "Thai Green Curry Bowl", Price: 289, Veg: true, Desc: "green curry · jasmine rice · basil · coconut milk", Kcal: 610, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "bc-smoothie-bowl", Name: "Acai Smoothie Bowl", Price: 249, Veg: true, Tag: "new", Desc: "acai blend · granola · banana · honey drizzle", Kcal: 340, Rating: 4.6, Section: catalog.SectionFood},
			{ID: "bc-miso-soup", Name: "Miso Soup", Price: 99, Veg: true, Desc: "white miso · tofu · wakame · spring onion", Kcal: 80, Rating: 4.3, Section: catalog.SectionFood},
			{ID: "bc-edamame", Name: "Salted Edamame", Price: 129, Veg: true, Desc: "steamed edamame · sea salt · chilli flakes", Kcal: 140, Rating: 4.4, Section: catalog.SectionFood},
			{ID: "bc-yuzu-lemonade", Name: "Yuzu Lemonade", Price: 149, Veg: true, Desc: "yuzu juice · honey · sparkling water · mint", Kcal: 75, Rating: 4.5, Section: catalog.SectionFood},
		}},
	// ---- snacks ----
	{ID: "whole-truth", Name: "The Whole Truth", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "35-45 min", Fav: true, Rating: 4.8,
		ServesAddressIDs: []string{"a1", "a2"}, Items: []catalog.Item{
			{ID: "wt-protein-bar", Name: "Protein Bar", Price: 90, Tag: "new", Veg: true, Desc: "20g protein · no added sugar", Kcal: 200, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "wt-pb-cup", Name: "Peanut Butter Cup", Price: 60, Veg: true, Desc: "dark chocolate · 7g protein", Kcal: 120, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "wt-choco-bar", Name: "Chocolate Protein Bar", Price: 95, Veg: true, Desc: "dark chocolate coating · 20g protein · no palm oil", Kcal: 210, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "wt-peanut-bar", Name: "Peanut Butter Protein Bar", Price: 90, Veg: true, Desc: "natural peanut butter · whey protein · no sugar", Kcal: 205, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "wt-almond-bar", Name: "Almond Nougat Bar", Price: 85, Veg: true, Desc: "roasted almonds · nougat · clean label", Kcal: 190, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "wt-dark-choco", Name: "Dark Chocolate (70%)", Price: 175, Veg: true, Desc: "single origin · 70% cocoa · no refined sugar", Kcal: 170, Rating: 4.8, Section: catalog.SectionSnacks},
			{ID: "wt-hazelnut-choco", Name: "Hazelnut Chocolate", Price: 185, Veg: true, Desc: "roasted hazelnut · milk chocolate · no palm oil", Kcal: 185, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "wt-granola", Name: "Muesli Granola Pack", Price: 199, Veg: true, Desc: "oats · mixed nuts · honey · no artificial flavour", Kcal: 220, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "wt-energy-ball", Name: "Energy Balls (6 pcs)", Price: 120, Veg: true, Desc: "dates · oats · cocoa · rolled in desiccated coconut", Kcal: 180, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "wt-trail-mix", Name: "Trail Mix", Price: 149, Veg: true, Desc: "cashew · almond · cranberry · dark choc chips", Kcal: 200, Rating: 4.5, Section: catalog.SectionSnacks},
		}},
	{ID: "snackible", Name: "Snackible", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "30-40 min", Rating: 4.3,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "sn-makhana", Name: "Roasted Makhana", Price: 99, Veg: true, Desc: "foxnuts · peri-peri · air-roasted", Kcal: 140, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "sn-chips", Name: "Baked Veggie Chips", Price: 79, Veg: true, Desc: "beetroot · kale · sea salt", Kcal: 160, Rating: 4.2, Section: catalog.SectionSnacks},
			{ID: "sn-popcorn", Name: "Himalayan Salt Popcorn", Price: 69, Veg: true, Desc: "air-popped · himalayan salt · 98% fat-free", Kcal: 110, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "sn-granola-bar", Name: "Oat Granola Bar", Price: 55, Veg: true, Desc: "rolled oats · honey · mixed seeds · no maida", Kcal: 130, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "sn-chia-crackers", Name: "Chia Seed Crackers", Price: 89, Veg: true, Desc: "whole wheat · chia seeds · rosemary · olive oil", Kcal: 150, Rating: 4.2, Section: catalog.SectionSnacks},
			{ID: "sn-choco-almonds", Name: "Chocolate Almonds", Price: 119, Veg: true, Desc: "dark chocolate coated · roasted almonds · dusted cocoa", Kcal: 175, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "sn-banana-chips", Name: "Kerala Banana Chips", Price: 59, Veg: true, Desc: "nendran banana · coconut oil · salted", Kcal: 190, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "sn-quinoa-puffs", Name: "Quinoa Puffs", Price: 99, Tag: "new", Veg: true, Desc: "puffed quinoa · black pepper · lime", Kcal: 105, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "sn-mixed-nuts", Name: "Roasted Mixed Nuts", Price: 149, Veg: true, Desc: "cashew · walnut · almond · pumpkin seed · sea salt", Kcal: 195, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "sn-protein-popcorn", Name: "Protein Popcorn", Price: 89, Veg: true, Desc: "7g protein per bag · cheese · whey coated", Kcal: 120, Rating: 4.1, Section: catalog.SectionSnacks},
		}},
	{ID: "open-secret", Name: "Open Secret", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "35-45 min", Fav: true, Rating: 4.6,
		ServesAddressIDs: []string{"a1", "a2"}, Items: []catalog.Item{
			{ID: "os-peanut-butter", Name: "Classic Peanut Butter", Price: 199, Veg: true, Desc: "just peanuts and salt · no palm oil · stone ground", Kcal: 190, Rating: 4.8, Section: catalog.SectionSnacks},
			{ID: "os-choco-pb", Name: "Choco Peanut Butter", Price: 215, Veg: true, Desc: "dark cocoa swirl · natural peanut butter · no added sugar", Kcal: 200, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "os-crunchy-pb", Name: "Crunchy Peanut Butter", Price: 199, Veg: true, Desc: "chunky roasted peanuts · himalayan salt · stone ground", Kcal: 195, Rating: 4.8, Section: catalog.SectionSnacks},
			{ID: "os-almond-butter", Name: "Almond Butter", Price: 299, Veg: true, Desc: "california almonds · raw · nothing else", Kcal: 180, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "os-granola-bar", Name: "Peanut Butter Granola Bar", Price: 55, Veg: true, Desc: "oats · peanut butter · honey · seeds", Kcal: 145, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "os-choco-bar", Name: "Chocolate Muesli Bar", Price: 55, Veg: true, Tag: "new", Desc: "rolled oats · dark choco chips · honey", Kcal: 140, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "os-coconut-ladoo", Name: "Coconut Ladoo (4 pcs)", Price: 99, Veg: true, Desc: "desiccated coconut · jaggery · cardamom", Kcal: 160, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "os-ragi-cookies", Name: "Ragi Cookies (6 pcs)", Price: 89, Veg: true, Desc: "finger millet · jaggery · ghee · no maida", Kcal: 180, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "os-trail-mix", Name: "Superfood Trail Mix", Price: 149, Veg: true, Desc: "goji berry · almond · pumpkin seed · dark choco", Kcal: 185, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "os-multigrain-chips", Name: "Multigrain Snack Chips", Price: 79, Veg: true, Desc: "corn · wheat · oats · no artificial colour", Kcal: 165, Rating: 4.3, Section: catalog.SectionSnacks},
		}},
	{ID: "yoga-bar", Name: "Yoga Bar", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "30-40 min", Rating: 4.4,
		ServesAddressIDs: []string{"a2", "a3"}, Items: []catalog.Item{
			{ID: "yb-protein-bar", Name: "Protein Bar Choco Fudge", Price: 85, Veg: true, Desc: "10g protein · dates · oats · dark chocolate", Kcal: 185, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "yb-multigrain-bar", Name: "Multigrain Energy Bar", Price: 55, Veg: true, Desc: "oats · millet · quinoa · seeds · honey", Kcal: 135, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "yb-muesli", Name: "Fruit & Nut Muesli", Price: 249, Veg: true, Desc: "whole oats · raisin · almond · cashew · no sugar", Kcal: 210, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "yb-overnight-oats", Name: "Overnight Oats Pack", Price: 149, Veg: true, Desc: "rolled oats · chia · flax · add milk and sleep", Kcal: 190, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "yb-peanut-bar", Name: "Peanut Chocolate Bar", Price: 65, Veg: true, Desc: "roasted peanuts · cocoa · jaggery · no maida", Kcal: 155, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "yb-seeds-mix", Name: "Power Seeds Mix", Price: 179, Veg: true, Desc: "pumpkin · sunflower · flax · sesame · roasted", Kcal: 165, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "yb-protein-cookie", Name: "Protein Cookie", Price: 75, Veg: true, Tag: "new", Desc: "oats · whey · choco chip · 8g protein per cookie", Kcal: 170, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "yb-honey", Name: "Raw Forest Honey", Price: 299, Veg: true, Desc: "unprocessed · wild harvest · single origin", Kcal: 60, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "yb-nut-butter", Name: "Almond Cashew Butter", Price: 349, Veg: true, Desc: "roasted almonds and cashews · himalayan salt only", Kcal: 190, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "yb-date-bites", Name: "Dark Chocolate Date Bites (5 pcs)", Price: 99, Veg: true, Desc: "medjool dates · dark chocolate coating · almonds inside", Kcal: 150, Rating: 4.5, Section: catalog.SectionSnacks},
		}},
	{ID: "beyond-snack", Name: "Beyond Snack", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "35-45 min", Rating: 4.5,
		ServesAddressIDs: []string{"a1", "a3"}, Items: []catalog.Item{
			{ID: "bs-nendran-chips", Name: "Nendran Banana Chips (Classic)", Price: 79, Veg: true, Desc: "kerala nendran · coconut oil · hand sliced · salted", Kcal: 195, Rating: 4.8, Section: catalog.SectionSnacks},
			{ID: "bs-masala-chips", Name: "Nendran Masala Chips", Price: 79, Veg: true, Desc: "nendran banana · house masala blend · spicy", Kcal: 190, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "bs-pepper-chips", Name: "Black Pepper Banana Chips", Price: 79, Veg: true, Desc: "nendran · cracked black pepper · coconut oil", Kcal: 190, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "bs-sweet-chips", Name: "Sweet Banana Chips", Price: 75, Veg: true, Desc: "nendran banana · jaggery glaze · light crunch", Kcal: 200, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "bs-jackfruit-chips", Name: "Jackfruit Chips", Price: 89, Veg: true, Tag: "new", Desc: "ripe jackfruit · coconut oil · sea salt · crisp", Kcal: 170, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "bs-tapioca-chips", Name: "Tapioca Chips", Price: 65, Veg: true, Desc: "kappa · coconut oil · red chilli · crispy", Kcal: 185, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "bs-rice-crackers", Name: "Puffed Rice Crackers", Price: 59, Veg: true, Desc: "puffed rice · sesame · chaat masala · light", Kcal: 120, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "bs-coconut-bites", Name: "Toasted Coconut Bites", Price: 89, Veg: true, Desc: "desiccated coconut · jaggery · cardamom · bite-sized", Kcal: 155, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "bs-mango-chips", Name: "Raw Mango Chips", Price: 75, Veg: true, Desc: "raw mango · chilli · salt · tangy crunch", Kcal: 140, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "bs-variety-pack", Name: "Chips Variety Pack (3 flavours)", Price: 199, Veg: true, Desc: "classic · masala · pepper · 3 packs of nendran chips", Kcal: 195, Rating: 4.8, Section: catalog.SectionSnacks},
		}},
	{ID: "happilo", Name: "Happilo", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "40-50 min", Rating: 4.3,
		ServesAddressIDs: []string{"a1", "a2", "a3"}, Items: []catalog.Item{
			{ID: "hp-premium-mix", Name: "Premium Nut Mix", Price: 199, Veg: true, Desc: "california walnut · cashew · almond · pistachio", Kcal: 195, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "hp-dried-cranberry", Name: "Dried Cranberries", Price: 169, Veg: true, Desc: "sweetened dried cranberry · no preservatives", Kcal: 130, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "hp-medjool-dates", Name: "Medjool Dates (250g)", Price: 299, Veg: true, Desc: "imported · soft · caramel-like · rich in iron", Kcal: 160, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "hp-raisins", Name: "Golden Raisins", Price: 119, Veg: true, Desc: "thompson seedless · sun-dried · sweet and plump", Kcal: 140, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "hp-cashews", Name: "Whole Cashews (200g)", Price: 249, Veg: true, Desc: "w240 grade · lightly salted · no oil added", Kcal: 180, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "hp-almonds", Name: "California Almonds (200g)", Price: 299, Veg: true, Desc: "raw · unblanched · heart-healthy · high vitamin E", Kcal: 170, Rating: 4.7, Section: catalog.SectionSnacks},
			{ID: "hp-pistachio", Name: "Roasted Pistachios", Price: 329, Veg: true, Tag: "new", Desc: "in-shell · lightly salted · slow roasted", Kcal: 160, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "hp-walnut-halves", Name: "Walnut Halves", Price: 279, Veg: true, Desc: "light halves · omega 3 rich · store cold", Kcal: 185, Rating: 4.6, Section: catalog.SectionSnacks},
			{ID: "hp-fig-almond-bar", Name: "Fig & Almond Bar", Price: 75, Veg: true, Desc: "dried fig · almond · sesame · no added sugar", Kcal: 145, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "hp-choco-coated-nuts", Name: "Dark Choco Coated Nuts", Price: 189, Veg: true, Desc: "almond · cashew · 70% dark chocolate coating", Kcal: 195, Rating: 4.7, Section: catalog.SectionSnacks},
		}},
	{ID: "eat-anytime", Name: "Eat Anytime", City: "Bangalore", Section: catalog.SectionSnacks, ETA: "30-40 min", Rating: 4.2,
		ServesAddressIDs: []string{"a2", "a3"}, Items: []catalog.Item{
			{ID: "ea-protein-chips", Name: "Protein Chips Spicy", Price: 69, Veg: true, Desc: "lentil-based · 5g protein · baked not fried", Kcal: 110, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "ea-roasted-chana", Name: "Roasted Chana Crunch", Price: 55, Veg: true, Desc: "kabuli chana · tangy masala · high protein", Kcal: 130, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "ea-oat-bar", Name: "Oat & Honey Bar", Price: 40, Veg: true, Desc: "rolled oats · honey · mixed seeds · no maida", Kcal: 115, Rating: 4.2, Section: catalog.SectionSnacks},
			{ID: "ea-energy-bar", Name: "Chocolate Energy Bar", Price: 50, Veg: true, Desc: "dates · cocoa · oats · whey protein · 6g protein", Kcal: 145, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "ea-baked-nachos", Name: "Baked Corn Nachos", Price: 75, Veg: true, Desc: "whole corn · baked · chilli lime · no palm oil", Kcal: 155, Rating: 4.1, Section: catalog.SectionSnacks},
			{ID: "ea-quinoa-chips", Name: "Quinoa Chips Salt & Vinegar", Price: 79, Veg: true, Tag: "new", Desc: "quinoa crisps · apple cider vinegar · sea salt", Kcal: 120, Rating: 4.5, Section: catalog.SectionSnacks},
			{ID: "ea-masala-peanuts", Name: "Masala Peanuts", Price: 45, Veg: true, Desc: "roasted · chilli · cumin · crispy batter", Kcal: 165, Rating: 4.3, Section: catalog.SectionSnacks},
			{ID: "ea-dry-fruit-bar", Name: "Dry Fruit & Nut Bar", Price: 65, Veg: true, Desc: "cashew · almond · raisin · pressed bar · no sugar", Kcal: 150, Rating: 4.4, Section: catalog.SectionSnacks},
			{ID: "ea-multigrain-khakra", Name: "Multigrain Khakra", Price: 89, Veg: true, Desc: "whole wheat · methi · sesame · crisp · light", Kcal: 135, Rating: 4.2, Section: catalog.SectionSnacks},
			{ID: "ea-green-tea-chips", Name: "Green Tea & Ginger Chips", Price: 79, Veg: true, Desc: "rice crisps · matcha · ginger · low calorie", Kcal: 100, Rating: 4.0, Section: catalog.SectionSnacks},
		}},
}

// instamartItems is the flat curated fast-lane list (no per-place grouping).
var instamartItems = []catalog.Item{
	{ID: "im-red-bull", Name: "Red Bull (250ml)", Price: 125, Section: catalog.SectionInstamart},
	{ID: "im-monster", Name: "Monster Energy", Price: 110, Section: catalog.SectionInstamart},
	{ID: "im-cold-brew-can", Name: "Sleepy Owl Cold Brew Can", Price: 99, Tag: "new", Section: catalog.SectionInstamart},
	{ID: "im-dark-choc", Name: "Lindt Dark Chocolate", Price: 180, Veg: true, Section: catalog.SectionInstamart},
	{ID: "im-lays", Name: "Lay's Classic Salted", Price: 20, Veg: true, Section: catalog.SectionInstamart},
	{ID: "im-bananas", Name: "Bananas (6)", Price: 49, Veg: true, Section: catalog.SectionInstamart},
	{ID: "im-sparkling", Name: "Sparkling Water", Price: 60, Veg: true, Section: catalog.SectionInstamart},
}

// usualPin is the editorial "the usual" preference; used when serviceable.
var usualPin = struct {
	PlaceID string
	ItemID  string
}{PlaceID: "blue-tokai", ItemID: "bt-cold-coffee"}
